import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layouts/Layout'
import Hero from '@/components/Hero/Hero'
import DietSection from '@/components/Diets'

export default function Home() {
  return (
    <div className="font-poppins">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <DietSection/>
      </Layout>
    </div>
  )
}
