import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layouts/Layout'
import Hero from '@/components/Hero/Hero'
import DietSection from '@/components/Diets'
import WhatYouGet from '@/components/WhatYouGet'
import SportSection from '@/components/SportsEvents'

export default function Home() {
  return (
    <div className="font-poppins">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <WhatYouGet/>
        <DietSection/>
        <div className='py-3 bg-gray-100'>
          
        <SportSection/>
        </div>
      </Layout>
    </div>
  )
}
